package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"tsplay/tsplay_core"

	"gopkg.in/yaml.v3"
)

const (
	quickstartDemoDirName  = "quickstart"
	quickstartDemoFlowName = "quickstart-demo.flow.yaml"
	quickstartDemoJSONName = "quickstart-demo-output.json"
)

type quickstartDemoActionResult struct {
	Action             string                  `json:"action"`
	PlaywrightRequired bool                    `json:"playwright_required"`
	GeneratedFlowPath  string                  `json:"generated_flow_path"`
	OutputJSONPath     string                  `json:"output_json_path"`
	RunResult          *tsplay_core.FlowResult `json:"run_result,omitempty"`
	NextSteps          []string                `json:"next_steps,omitempty"`
}

func buildQuickstartDemoFlow(outputPath string) *tsplay_core.Flow {
	return &tsplay_core.Flow{
		SchemaVersion: tsplay_core.CurrentFlowSchemaVersion,
		Name:          "quickstart_demo",
		Description:   "Generated by -action quickstart-demo. This demo only uses data actions and does not require Playwright.",
		Steps: []tsplay_core.FlowStep{
			{
				Name:   "set greeting",
				Action: "set_var",
				SaveAs: "greeting",
				Value:  "hello from tsplay quickstart",
			},
			{
				Name:   "build payload",
				Action: "set_var",
				SaveAs: "payload",
				With: map[string]any{
					"value": map[string]any{
						"demo":                "quickstart",
						"mode":                "flow",
						"greeting":            "{{greeting}}",
						"playwright_required": false,
						"next_step":           "run a browser flow only when you want page automation",
					},
				},
			},
			{
				Name:     "write quickstart output",
				Action:   "write_json",
				FilePath: outputPath,
				Value:    "{{payload}}",
			},
		},
	}
}

func runQuickstartDemoAction(artifactRoot string, headless bool) (*quickstartDemoActionResult, error) {
	trimmedRoot := strings.TrimSpace(artifactRoot)
	if trimmedRoot == "" {
		trimmedRoot = tsplay_core.DefaultFlowArtifactRoot
	}

	quickstartDir := filepath.Join(trimmedRoot, quickstartDemoDirName)
	if err := os.MkdirAll(quickstartDir, 0o755); err != nil {
		return nil, fmt.Errorf("create quickstart dir: %w", err)
	}

	flowPath := filepath.Join(quickstartDir, quickstartDemoFlowName)
	outputPath := filepath.Join(quickstartDir, quickstartDemoJSONName)
	flow := buildQuickstartDemoFlow(filepath.ToSlash(outputPath))

	encoded, err := yaml.Marshal(flow)
	if err != nil {
		return nil, fmt.Errorf("marshal quickstart flow: %w", err)
	}
	if err := os.WriteFile(flowPath, encoded, 0o644); err != nil {
		return nil, fmt.Errorf("write quickstart flow: %w", err)
	}

	result, runErr := tsplay_core.RunFlow(flow, tsplay_core.FlowRunOptions{
		Headless:     headless,
		ArtifactRoot: trimmedRoot,
	})

	actionResult := &quickstartDemoActionResult{
		Action:             "quickstart-demo",
		PlaywrightRequired: false,
		GeneratedFlowPath:  flowPath,
		OutputJSONPath:     outputPath,
		RunResult:          result,
		NextSteps: []string{
			"./tsplay -action file-srv -addr :8000",
			"./tsplay -flow script/tutorials/10_assert_page_state.flow.yaml",
			"./tsplay -action extract-assets -extract-root ./tsplay-assets",
		},
	}
	if runErr != nil {
		return actionResult, runErr
	}
	return actionResult, nil
}
