---
--- Generated by Luanalysis
--- Created by tensafe.
--- DateTime: 2025/3/1 16:28
---

navigate("https://www.baidu.com")
-- 设置请求拦截器
abc = get_response("https://ug.baidu.com/mcp/pc/pcsearch")
print(abc)
